---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidycensus")
library("tidyverse")
library("terra")
library("tmap")
library("mapview")
library("rosm")
library("crsuggest")
library("tigris")
library("sf")
library("leafsync")
```

```{r}
# mo_race <- get_decennial(
#   geography = "tract",
#   state = "MO",
#   variables = c(
#     Hispanic = "P2_002N",
#     White = "P2_005N",
#     Black = "P2_006N",
#     Native = "P2_007N",
#     Asian = "P2_008N"
#   ),
#   summary_var = "P2_001N",
#   year = 2020,
#   geometry = TRUE
# ) %>%
#   mutate(percent = 100 * (value / summary_value))
```
```{r}
# mo_black <- filter(mo_race, 
#                          variable == "Black")
# tm_shape(mo_black) + 
#   tm_polygons(col = "percent")
```

```{r}
# mo_black <- filter(mo_race, 
#                          variable == "Black")
# tm_shape(mo_black) + 
#   tm_polygons(col = "percent",
#               style = "quantile",
#               n = 7,
#               palette = "Purples",
#               title = "2020 US Census") +
#    tm_layout(title = "Percent Black\nby Census tract",
#             frame = FALSE,
#             legend.outside = TRUE)
```

```{r}
# tm_shape(mo_race) + 
#   tm_facets(by = "variable", scale.factor = 4) + 
#   tm_fill(col = "percent",
#           style = "quantile",
#           n = 7,
#           palette = "Blues") + 
#   tm_layout(legend.position = c(-0.7, 0.15))


```
#Home value
```{r}
years <- 2011:2020
names(years) <- years

mo_value <- map_dfr(years, ~{
  get_acs(
    geography = "state",
    variables = "B25077_001",
    state = "MO",
    year = .x,
    survey = "acs5"
  )
}, .id = "year")

```

```{r}
ggplot(mo_value, aes(x = year, y = estimate, group = 1)) +
  geom_ribbon(aes(ymax = estimate + moe, ymin = estimate - moe),
              fill = "navy",
              alpha = 0.5) +
  geom_line(color = "navy") +
  geom_point(color = "navy", size = 2) +
  theme_minimal(base_size = 12) +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Median home value in Missouri",
       x = "Year",
       y = "ACS estimate",
       caption = "Shaded area represents margin of error around the ACS estimate")

ggsave("mo_value.png")
```

```{r}
mo_value2 <- get_acs(
  geography = "county",
  variables = "B25077_001",
  state = "MO",
  geometry = TRUE,
  year = 2020
) %>% arrange(desc(estimate))
```


```{r}
years <- 2011:2020
names(years) <- years

mo_income <- map_dfr(years, ~{
  get_acs(
    geography = "state",
    variables = "B19013_001",
    state = "MO",
    year = .x,
    survey = "acs5"
  )
}, .id = "year")
```

```{r}
ggplot(mo_income, aes(x = year, y = estimate, group = 1)) +
  geom_ribbon(aes(ymax = estimate + moe, ymin = estimate - moe),
              fill = "navy",
              alpha = 0.5) +
  geom_line(color = "darkgreen") +
  geom_point(color = "darkgreen", size = 2) +
  theme_minimal(base_size = 12) +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Median income in Missouri 2011-2020",
       x = "Year",
       y = "ACS estimate",
       caption = "Shaded area represents margin of error around the ACS estimate")

ggsave("mo_income.png")
```

```{r}
mo_income2 <- get_acs(
  geography = "county",
  variables = "B19013_001",
  state = "MO",
  geometry = TRUE,
  year = 2020
)
```

```{r}
mo_income3 <- mo_income2 %>% arrange(desc(estimate))
```


```{r}
mo_income2 %>% ggplot(
  aes(fill = estimate)) +
  geom_sf() +
  scale_fill_distiller(palette = "PuBu",
                       direction = 1) +
  labs(title = "Missouri Median Income by County, 2020",
       caption = "Data source: 2020 5-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void()

#ggsave("mo_income2.png")
```
```{r}
mo_median_age <- get_acs(
  geography = "county",
  variables = "B01002_001",
  state = "MO",
  year = 2020,
  geometry = TRUE,
  resolution = "20m"
) 

mo_median_age %>% ggplot(
  aes(fill = estimate)) +
  geom_sf() +
  scale_fill_distiller(palette = "PuBu",
                       direction = 1) +
  labs(title = "Missouri Median Age by County, 2020",
       caption = "Data source: 2020 5-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void()
```


```{r}
us_value <- get_acs(
  geography = "state",
  variables = "B25077_001",
  year = 2020,
  geometry = TRUE,
  resolution = "20m"
)
```
```{r}
us_value2 <- us_value %>% arrange(desc(estimate))
```

```{r}
us_value_shifted <- us_value %>% 
  shift_geometry(position = "outside") %>% 
  mutate(tooltip = paste(NAME, estimate, sep = ": "))

gg <- ggplot(us_value_shifted, aes(fill = estimate)) +
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME),
                      size = 0.1) +
  scale_fill_viridis_c(option = "viridis", labels = scales::dollar, direction = -1) +
  labs(title = "Median  value by State, 2020",
       caption = "Data source: 2020 5-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void() +

girafe(ggobj = gg) %>% 
  girafe_options(opts_hover(css = "fill:cyan;"),
                 opts_zoom(max = 10))

ggsave("us_value_shifted.png")
```

```{r}
us_income <- get_acs(
  geography = "state",
  variables = "B19013_001",
  year = 2020,
  geometry = TRUE,
  resolution = "20m"
)
```

```{r}
us_income2 <- us_income %>% arrange(desc(estimate))
```


```{r}
us_income_shifted <- us_income %>% 
  shift_geometry(position = "outside") %>% 
  mutate(tooltip = paste(NAME, estimate, sep = ": "))

gg <- ggplot(us_income_shifted, aes(fill = estimate)) +
  geom_sf_interactive(aes(tooltip = tooltip, data_id = NAME),
                      size = 0.1) +
  scale_fill_viridis_c(option = "viridis", labels = scales::dollar, direction = -1) +
  labs(title = "Median income by State, 2020",
       caption = "Data source: 2020 5-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void()

girafe(ggobj = gg) %>% 
  girafe_options(opts_hover(css = "fill:cyan;"),
                 opts_zoom(max = 10))

ggsave("us_income_shifted.png")
```

```{r}
neighbor_income <- us_income %>% filter(NAME == "Missouri" | NAME=="Illinois" | NAME=="Kansas" | NAME=="Arkansas" | NAME=="Iowa" | NAME=="Tennessee" | NAME=="Oklahoma")
```


```{r}
us_map <- ggplot(neighbor_income, aes(fill = estimate)) +
  geom_sf_interactive(aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "PuBu",
                       direction = 1,
                       guide = "none") +
  theme_void()

us_plot <- ggplot(neighbor_income, aes(x = estimate, y = reorder(NAME, estimate), fill = estimate)) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21,
                         aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "PuBu", direction = 1,
                       labels = scales::dollar) +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "Median household income of Missouri and neighbor states",
       subtitle = "2016 - 2020 American Community Survey",
       y = "",
       x = "ACS estimate",
       fill = "ACS estimate") +
  theme_minimal(base_size = 14)

girafe(ggobj = us_map + us_plot, width_svg = 10, height_svg = 5) %>% 
  girafe_options(opts_hover(css = "fill:cyan;"))

ggsave("us_map.png")
ggsave("us_plot.png")
```

```{r}
neighbor_value <- us_value %>% filter(NAME == "Missouri" | NAME=="Illinois" | NAME=="Kansas" | NAME=="Arkansas" | NAME=="Iowa" | NAME=="Tennessee" | NAME=="Oklahoma")
```

```{r}
us_map1 <- ggplot(neighbor_value, aes(fill = estimate)) +
  geom_sf_interactive(aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "PuBu",
                       direction = 1,
                       guide = "none") +
  theme_void()

us_plot1 <- ggplot(neighbor_value, aes(x = estimate, y = reorder(NAME, estimate), fill = estimate)) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21,
                         aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "PuBu", direction = 1,
                       labels = scales::dollar) +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "Median home value of Missouri and neighbor states",
       subtitle = "2016 - 2020 American Community Survey",
       y = "",
       x = "ACS estimate",
       fill = "ACS estimate") +
  theme_minimal(base_size = 14)

girafe(ggobj = us_map1 + us_plot1, width_svg = 10, height_svg = 5) %>% 
  girafe_options(opts_hover(css = "fill:cyan;"))
```

```{r}
# median_income1 <- get_acs(
#   geography = "tract",
#   variables = "B19013_001",
#   state = "MO",
#   county = c(
#     "Boone",
#     "St. Charles",
#     "Platte",
#     "St. Louis County",
#     "Jefferson"
#   ),
#   year = 2020
# )
# 
# median_income1 <- separate(
#   median_income1,
#   NAME,
#   into = c("tract", "county", "state"),
#   sep = ", "
# )
# 
# median_income1 %>% 
#   group_by(county) %>% 
#   summarise(min = min(estimate, na.rm = TRUE),
#             mean = mean(estimate, na.rm = TRUE),
#             median = median(estimate, na.rm = TRUE),
#             max = max(estimate, na.rm = TRUE))
```

```{r}
# ggplot(median_income1, aes(x = estimate, y = county)) +
#   geom_density_ridges() +
#   theme_ridges() +
#   labs(x= "Median income: 2016 - 2020 ACS estimate",
#        y = "") +
#   scale_x_continuous(labels = scales::dollar)
```

